### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by DokaRus** [roman-usov/frontend-project-46#1]
https://github.com/roman-usov/frontend-project-46/blob/51bdcfd602dbe24f261fac18fda762f0b862e7f6/package.json#L8

У тебя jest итак в dev-dependencies, можно написать просто `"test": "jest"`

https://github.com/roman-usov/frontend-project-46/blob/51bdcfd602dbe24f261fac18fda762f0b862e7f6/package.json#L5

Использовать `src/target_script_name` (т.е. **исходных код** программы) как основной entry point, как правило, плохая идея. У тебя внутри современный ES + если данный репозиторий будет публиковаться как пакет; то при его установке, как зависимости, devDependencies **не затягиваются**. Использование бандлеров (webpack/vite/parcel etc) решает задачу сбоки сайта/скрипта/либы для работы на целевой платформе (т.е. учитываются всякие нюансы запуска скрипта в браузере, на ноде и т.п.).
Не думал в рамках этого проекта подрубить тот же вебпак и собирать бандл в `/dist` или `/lib`? 

Для исходников - обычно, главный entry-point - файл `index.js`

https://github.com/roman-usov/frontend-project-46/blob/51bdcfd602dbe24f261fac18fda762f0b862e7f6/src/genDiffForFlatObjs.js#L3-L7

У тебя обращения к этим константам итак идут в виде
```
status: STATUS.added
```
и т.п. Константы не вынесены в какой-то отдельный файл, друггих групп тут нет.  Можно не группировать, код будет вполне понятен и без дублирования
```
status: REMOVED
```

Вот тут
https://github.com/roman-usov/frontend-project-46/blob/51bdcfd602dbe24f261fac18fda762f0b862e7f6/src/parsers.js#L5-L10
Зачем это выносить? Это не "magic numbers", смысл понятен + нет переиспользования где-либо
```
    case 'json': {
      return parseJson(fileContent);
    }
    case 'yaml':
    case 'yml': {
      return parseYaml(fileContent);
    }
```
Если в контексте парсеров хочется каких-то наворотов (не с практической точки зрения, а потренироваться), то можно попробовать организовать данные по типу плагинов - к примеру, завести контроллер и  вынести в него логику регистрации парсеров + геттеров обработчиков)

https://github.com/roman-usov/frontend-project-46/blob/51bdcfd602dbe24f261fac18fda762f0b862e7f6/src/genDiffForFlatObjs.js#L1

Нет необходимости тянуть всю либу ради пары функций. Можно импортнуть отдельно
https://www.npmjs.com/package/lodash.has
https://www.npmjs.com/package/lodash.sortby

**Comment by roman-usov** [comment]
> У тебя jest итак в dev-dependencies, можно написать просто "test": "jest"

Поправил. Действительно, насколько помню, npx можно использовать для запуска пакета без его установки. Вроде, так?

**Comment by roman-usov** [comment]
> Для исходников - обычно, главный entry-point - файл index.js
Да, согласен. Сделал точкой входа index.js

`import genDiffForFlatObjs from './src/genDiffForFlatObjs.js';
import parseFile from './src/parsers.js';

export default function genDiff(originalFilePath, changedFilePath) {
  return genDiffForFlatObjs(parseFile(originalFilePath), parseFile(changedFilePath));
}`

Там живет одна лишь функция по умолчанию, которая использует весь остальной исходный код. 
По остальным поинтам ща еще кое-что у тебя уточню.

**Comment by roman-usov** [comment]
> У тебя внутри современный ES + если данный репозиторий будет публиковаться как пакет; то при его установке, как зависимости, devDependencies не затягиваются.

Надеюсь, правильно понял. Если мы устанавливаем пакет, как зависимость, то нам и не нужно, чтобы устанавливались devDependencies, т.к. они нужны для разработки подключаемого пакета. А для использования достаточно только основных зависимостей. Или я не так понял?

**Comment by roman-usov** [comment]
> Константы не вынесены в какой-то отдельный файл, друггих групп тут нет. Можно не группировать, код будет вполне понятен и без дублирования
Согласен, поправил.

**Comment by roman-usov** [comment]
> Нет необходимости тянуть всю либу ради пары функций. Можно импортнуть отдельно

Точно, разобрался, теперь установил только нужные функции из либы и использую их.

**Comment by roman-usov** [comment]
> Если в контексте парсеров хочется каких-то наворотов (не с практической точки зрения, а потренироваться), то можно попробовать организовать данные по типу плагинов - к примеру, завести контроллер и вынести в него логику регистрации парсеров + геттеров обработчиков)

Вот это так не осилю с нескольких строчек. Может, получится, вместе сделать? Я так подозреваю, это нужно на классах сделать? Просто в этом проекте условие изначально - не используйте классы. дождитесь модуля по ООП.

**Comment by roman-usov** [comment]
> Использование бандлеров (webpack/vite/parcel etc) решает задачу сбоки сайта/скрипта/либы для работы на целевой платформе (т.е. учитываются всякие нюансы запуска скрипта в браузере, на ноде и т.п.).
Не думал в рамках этого проекта подрубить тот же вебпак и собирать бандл в /dist или /lib?

В других проектах использовал parcel. В этом проекте пока этого не требуют. Думаю, что бандлеры появятся в следующих модулях курса.

**Comment by roman-usov** [comment]
Еще пара вопросов. 

У меня сейчас реализация построена так. 
Первым шагом я собираю информацию об изменениях в структуру, используя отдельные функции для получения измененных, удаленных, добавленных и не измененных entries. 

```javascript
[
  { follow: { value: false, status: '-' } },
  { host: { value: 'hexlet.io', status: ' ' } },
  { proxy: { value: '123.234.53.22', status: '-' } },
  { timeout: { value: 50, status: '-' } },
  { timeout: { value: 20, status: '+' } },
  { verbose: { value: true, status: '+' } }
]
```
А вторым шагом прохожусь по этой структуре и вывожу изменения в ожидаемом формате

```
{
  - follow: false
    host: hexlet.io
  - proxy: 123.234.53.22
  - timeout: 50
  + timeout: 20
  + verbose: true
}
```
Ок ли такой подход? У меня вообще сначала была одна функция на reduce-е, которая по условиям сравнивала entries в каждом объекте и в зависимости от того, какое условие подошло, формировала строку нужного формата. Но code climate заругался, сказал, что слишком высокая cognitive complexity. Поэтому я разбил на отдельные операции: найди добавленные/удаленные, найди измененные, найди не измененные, собери результат, отформатируй... И тогда code climate успокоился.

**Comment by roman-usov** [comment]
У меня ща code climate ругается на то, что я использую дублирующиеся вещи в разных тестах. 

<img width="818" alt="CleanShot 2023-03-07 at 11 17 50@2x" src="https://user-images.githubusercontent.com/66104246/223351639-d69a5947-c784-4881-875e-8ffad1443a90.png">

И чёт не могу придумать, как это можно устранить. Или забить?

**Comment by DokaRus** [comment]
>Надеюсь, правильно понял. Если мы устанавливаем пакет, как зависимость, то нам и не нужно, чтобы устанавливались devDependencies, т.к. они нужны для разработки подключаемого пакета. А для использования достаточно только основных зависимостей. Или я не так понял?

devDependencies 
- устанавливаются, когда ты скачиваешь репозиторий пакета для того, чтобы ты могу чего-то доработать - это те зависимости, которые нужны для тестирования (всякие jest, chai, mocha, cypress), сборки(webpack, parcel), линтинга и т.п.
- не устанавливаются, когда пакет устанавливается как зависимость. 

В качестве примера - есть старенький движок-шаблонизатор mustache - у него нет зависимостей, только devDependencies. Если я его добавлю в свой проект, то у меня затянется **только** пакет mustache, без его devDependencies (и если он внутри завязан на использование чего-то из devDependencies - то функционал пакета будет поломан)
![image](https://user-images.githubusercontent.com/1554153/223564426-316030a4-d1ad-49ba-bc92-7858b7110766.png)

Однако, есть нюанс. В devDependencies может быть что-то, что зашивается внутрь пакета при сборке (т.е. пакет де-факто использует это в своей внутренней логике, но как зависимость не тянет) - обычно это всякие полифиллы (core-js, который, в общем-то и внутри babel используется).

**Comment by DokaRus** [comment]
>Вот это так не осилю с нескольких строчек. Может, получится, вместе сделать? Я так подозреваю, это нужно на классах сделать? Просто в этом проекте условие изначально - не используйте классы. дождитесь модуля по ООП.

Ну в js классы - "синтаксический сахар" над объектами, по сути. В данном случае это скорее переосытнением будет :) Так что что-то типа контроллера можно и как объект, и как класс описать. На примере класса это может быть что-то типа

```
class ParserController {
    constructor() {
        this._parsers= {};
    }

    addParser(name, parser) {
       // Тут также стоит добавить проверку параметров
        this._parsers[name] = parser;
    }

    getParser(name) {
        return this._parsers[name] || () => null;
    }
}

const parserController = new ParserController();

export { parserController };
```

Т.е. чего выше происходит - при загрузке кода инициируется класс и создаётся его инстанс в единичном экземпляре. Этот же инстанс данный модуль и экспортирует (т.е. можем сказать, что тут мы применяем 2 паттерна проектирования - контроллер и синглтон)

"Плагины" могут быть саморегистирующимися
```
// yaml-parser.js
import jsYaml from 'js-yaml';
import { parserController } from './parser-controller'

function parseYaml(fileContent) {
  return jsYaml.load(fileContent, 'utf8');
}

parserController.addParser('yml', parseYaml);
parserController.addParser('yaml', parseYaml);
```
 и  parseFile можно как-то так зарефакторить
```
// parsers.js
import './yaml-parser'; // мы просто единожды импортируем файл, чтобы он выполнился и зарегистрировал парсер
import { parserController } from './parser-controller';

export default function parseFile(filePath) {
  const fileExt = getFileExtension(filePath);
  const fileContent = fs.readFileSync(getAbsolutePath(filePath));
 
  return parserController.getParser(fileExt)(fileContent)
}
```
Ну и ты, при желании, можешь как-то извне давать возможность подключать новые парсеры (к примеру, сканировать текущую папку по какому-то паттерну, или высовывать наружу какую-то апишку - не суть важно)

**Comment by DokaRus** [comment]
> В других проектах использовал parcel. В этом проекте пока этого не требуют. Думаю, что бандлеры появятся в следующих модулях курса.

Ну, из такого прям очевидного - в текущем виде, если не заморачиваться с бандлером, по проекту есть ограничение по ноде (ёмнип, ES6 модули там с 12 версии включены) - на стареньких нодах надо через commonJS модули писать (`require`, `module.exports`)

**Comment by DokaRus** [comment]
>У меня ща code climate ругается на то, что я использую дублирующиеся вещи в разных тестах.

Ну, у тебя там реально 3 одинаковых теста, по сути :)
Как вариант, можно попробовать шаблонизировать

```
[
   {
      name: 'json',
      originalFileAbsPath: getAbsolutePath('src/__tests__/__fixtures__/main-flow-case/file1.json'),
      changedFileRelPath: 'src/__tests__/__fixtures__/main-flow-case/file2.json',
    },
    {
      name: 'yaml',
      originalFileAbsPath: getAbsolutePath('src/__tests__/__fixtures__/main-flow-case/file1.yaml'),
      changedFileRelPath: 'src/__tests__/__fixtures__/main-flow-case/file2.yml',
    },
   {
      name: 'json+yaml',
      originalFileAbsPath: getAbsolutePath('src/__tests__/__fixtures__/main-flow-case/file1.json'),
      changedFileRelPath: 'src/__tests__/__fixtures__/main-flow-case/file2.yml',
    },
  ].forEach(({ name, originalFileAbsPath, changedFileRelPath }) => {
    test(`it should display unchanged and changed lines for ${name}`, () => {
      expect(
        genDiff(testPathNames.json.originalFileAbsPath, testPathNames.json.changedFileRelPath),
      ).toEqual(expectedResult);
    });
});
```

**Comment by roman-usov** [comment]
> devDependencies

устанавливаются, когда ты скачиваешь репозиторий пакета для того, чтобы ты могу чего-то доработать - это те зависимости, которые нужны для тестирования (всякие jest, chai, mocha, cypress), сборки(webpack, parcel), линтинга и т.п.
не устанавливаются, когда пакет устанавливается как зависимость.
В качестве примера - есть старенький движок-шаблонизатор mustache - у него нет зависимостей, только devDependencies. Если я его добавлю в свой проект, то у меня затянется только пакет mustache, без его devDependencies (и если он внутри завязан на использование чего-то из devDependencies - то функционал пакета будет поломан)

Ага, принял, спасибо! 👍🏻

**Comment by roman-usov** [comment]
> На примере класса это может быть что-то типа

Крутая тема, очень понравилось! Порадовало, что мы так вообще избавляемся от логики с условиями. Просто дай тип нужного тебе парсера, я тебе такой парсер предоставлю. 
Я ее попробовал в проекте сделать. Все проверки локально и на code climate проходят. А вшитые хекслетовские проверки падают. И какой-то вменяемой инфы они не дают. Пока откатил назад. А код сохранил на replit.

**Comment by roman-usov** [comment]
> Ну, из такого прям очевидного - в текущем виде, если не заморачиваться с бандлером, по проекту есть ограничение по ноде (ёмнип, ES6 модули там с 12 версии включены) - на стареньких нодах надо через commonJS модули писать (require, module.exports)

Это да, такое ограничение сейчас есть. Но пока в проекте явно сказано использовать ES6 модули.

**Comment by roman-usov** [comment]
> Ну, у тебя там реально 3 одинаковых теста, по сути :)
> Как вариант, можно попробовать шаблонизировать

Блин, Семён Семёныч, так же все очевидно)) Вот уже ум за разум у меня зашел)) Спасибо)
